// @generated by tools/icon-atlas/generate-phosphor-icons.mjs

use kinetik_ui::core::{ImageId, Rect};

pub(super) struct PhosphorIconEntry {
    pub image: ImageId,
    pub symbol: &'static str,
    pub source_name: &'static str,
    pub source: Rect,
}

pub(super) const ICON_ATLAS: ImageId = ImageId::from_raw(7_000);
pub(super) const ICON_ATLAS_WIDTH: u32 = 238;
pub(super) const ICON_ATLAS_HEIGHT: u32 = 136;
pub(super) const ICON_SIZE: u32 = 32;
pub(super) const ICON_ATLAS_PADDING: u32 = 1;
pub(super) const ICON_ATLAS_CELL_SIZE: u32 = 34;
pub(super) const ICON_ATLAS_COLUMNS: u32 = 7;
pub(super) const ICON_ATLAS_ROWS: u32 = 4;
pub(super) const ICON_ATLAS_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas.rgba"));

pub(super) const ICON_CURSOR: ImageId = ImageId::from_raw(7001);
pub(super) const ICON_MOVE: ImageId = ImageId::from_raw(7002);
pub(super) const ICON_TRANSFORM: ImageId = ImageId::from_raw(7003);
pub(super) const ICON_ROTATE: ImageId = ImageId::from_raw(7004);
pub(super) const ICON_CUBE: ImageId = ImageId::from_raw(7005);
pub(super) const ICON_PLAY: ImageId = ImageId::from_raw(7006);
pub(super) const ICON_PAUSE: ImageId = ImageId::from_raw(7007);
pub(super) const ICON_STOP: ImageId = ImageId::from_raw(7008);
pub(super) const ICON_PLUS: ImageId = ImageId::from_raw(7009);
pub(super) const ICON_SEARCH: ImageId = ImageId::from_raw(7010);
pub(super) const ICON_ARCHIVE: ImageId = ImageId::from_raw(7011);
pub(super) const ICON_FILE: ImageId = ImageId::from_raw(7012);
pub(super) const ICON_IMAGE: ImageId = ImageId::from_raw(7013);
pub(super) const ICON_GEAR: ImageId = ImageId::from_raw(7014);
pub(super) const ICON_GRID: ImageId = ImageId::from_raw(7015);
pub(super) const ICON_LAYERS: ImageId = ImageId::from_raw(7016);
pub(super) const ICON_CODE: ImageId = ImageId::from_raw(7017);
pub(super) const ICON_BOX: ImageId = ImageId::from_raw(7018);
pub(super) const ICON_ROCKET: ImageId = ImageId::from_raw(7019);
pub(super) const ICON_DOWNLOAD: ImageId = ImageId::from_raw(7020);
pub(super) const ICON_DOTS: ImageId = ImageId::from_raw(7021);
pub(super) const ICON_CHEVRON: ImageId = ImageId::from_raw(7022);
pub(super) const ICON_CARET: ImageId = ImageId::from_raw(7023);
pub(super) const ICON_RESET: ImageId = ImageId::from_raw(7024);
pub(super) const ICON_COMPONENT: ImageId = ImageId::from_raw(7025);
pub(super) const ICON_TOKENS: ImageId = ImageId::from_raw(7026);
pub(super) const ICON_EYE: ImageId = ImageId::from_raw(7027);
pub(super) const ICON_CROSSHAIR: ImageId = ImageId::from_raw(7028);

pub(super) const ICON_ENTRIES: &[PhosphorIconEntry] = &[
    PhosphorIconEntry {
        image: ICON_CURSOR,
        symbol: "ICON_CURSOR",
        source_name: "cursor",
        source: Rect::new(1.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_MOVE,
        symbol: "ICON_MOVE",
        source_name: "arrows-out-cardinal",
        source: Rect::new(35.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_TRANSFORM,
        symbol: "ICON_TRANSFORM",
        source_name: "bounding-box",
        source: Rect::new(69.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_ROTATE,
        symbol: "ICON_ROTATE",
        source_name: "arrow-clockwise",
        source: Rect::new(103.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_CUBE,
        symbol: "ICON_CUBE",
        source_name: "cube",
        source: Rect::new(137.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_PLAY,
        symbol: "ICON_PLAY",
        source_name: "play",
        source: Rect::new(171.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_PAUSE,
        symbol: "ICON_PAUSE",
        source_name: "pause",
        source: Rect::new(205.0, 1.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_STOP,
        symbol: "ICON_STOP",
        source_name: "stop",
        source: Rect::new(1.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_PLUS,
        symbol: "ICON_PLUS",
        source_name: "plus",
        source: Rect::new(35.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_SEARCH,
        symbol: "ICON_SEARCH",
        source_name: "magnifying-glass",
        source: Rect::new(69.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_ARCHIVE,
        symbol: "ICON_ARCHIVE",
        source_name: "archive",
        source: Rect::new(103.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_FILE,
        symbol: "ICON_FILE",
        source_name: "file",
        source: Rect::new(137.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_IMAGE,
        symbol: "ICON_IMAGE",
        source_name: "image",
        source: Rect::new(171.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_GEAR,
        symbol: "ICON_GEAR",
        source_name: "gear",
        source: Rect::new(205.0, 35.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_GRID,
        symbol: "ICON_GRID",
        source_name: "grid-four",
        source: Rect::new(1.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_LAYERS,
        symbol: "ICON_LAYERS",
        source_name: "stack",
        source: Rect::new(35.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_CODE,
        symbol: "ICON_CODE",
        source_name: "code",
        source: Rect::new(69.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_BOX,
        symbol: "ICON_BOX",
        source_name: "package",
        source: Rect::new(103.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_ROCKET,
        symbol: "ICON_ROCKET",
        source_name: "rocket",
        source: Rect::new(137.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_DOWNLOAD,
        symbol: "ICON_DOWNLOAD",
        source_name: "download",
        source: Rect::new(171.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_DOTS,
        symbol: "ICON_DOTS",
        source_name: "dots-three",
        source: Rect::new(205.0, 69.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_CHEVRON,
        symbol: "ICON_CHEVRON",
        source_name: "caret-right",
        source: Rect::new(1.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_CARET,
        symbol: "ICON_CARET",
        source_name: "caret-down",
        source: Rect::new(35.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_RESET,
        symbol: "ICON_RESET",
        source_name: "arrow-counter-clockwise",
        source: Rect::new(69.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_COMPONENT,
        symbol: "ICON_COMPONENT",
        source_name: "circles-four",
        source: Rect::new(103.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_TOKENS,
        symbol: "ICON_TOKENS",
        source_name: "swatches",
        source: Rect::new(137.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_EYE,
        symbol: "ICON_EYE",
        source_name: "eye",
        source: Rect::new(171.0, 103.0, 32.0, 32.0),
    },
    PhosphorIconEntry {
        image: ICON_CROSSHAIR,
        symbol: "ICON_CROSSHAIR",
        source_name: "crosshair",
        source: Rect::new(205.0, 103.0, 32.0, 32.0),
    },
];
