// @generated by tools/icon-atlas/generate-phosphor-icons.mjs

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/phosphor_icons/types.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/phosphor_icons/atlases.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/phosphor_icons/entries.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/phosphor_icons/lookup.rs"));
