// @generated by tools/icon-atlas/generate-phosphor-icons.mjs

pub(crate) const ICON_ATLAS_16: ImageId = ImageId::from_raw(70016);
pub(crate) const ICON_ATLAS_16_WIDTH: u32 = 126;
pub(crate) const ICON_ATLAS_16_HEIGHT: u32 = 72;
pub(crate) const ICON_ATLAS_16_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-16.rgba"));
pub(crate) const ICON_ATLAS_20: ImageId = ImageId::from_raw(70020);
pub(crate) const ICON_ATLAS_20_WIDTH: u32 = 154;
pub(crate) const ICON_ATLAS_20_HEIGHT: u32 = 88;
pub(crate) const ICON_ATLAS_20_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-20.rgba"));
pub(crate) const ICON_ATLAS_24: ImageId = ImageId::from_raw(70024);
pub(crate) const ICON_ATLAS_24_WIDTH: u32 = 182;
pub(crate) const ICON_ATLAS_24_HEIGHT: u32 = 104;
pub(crate) const ICON_ATLAS_24_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-24.rgba"));
pub(crate) const ICON_ATLAS_28: ImageId = ImageId::from_raw(70028);
pub(crate) const ICON_ATLAS_28_WIDTH: u32 = 210;
pub(crate) const ICON_ATLAS_28_HEIGHT: u32 = 120;
pub(crate) const ICON_ATLAS_28_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-28.rgba"));
pub(crate) const ICON_ATLAS_30: ImageId = ImageId::from_raw(70030);
pub(crate) const ICON_ATLAS_30_WIDTH: u32 = 224;
pub(crate) const ICON_ATLAS_30_HEIGHT: u32 = 128;
pub(crate) const ICON_ATLAS_30_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-30.rgba"));
pub(crate) const ICON_ATLAS_32: ImageId = ImageId::from_raw(70032);
pub(crate) const ICON_ATLAS_32_WIDTH: u32 = 238;
pub(crate) const ICON_ATLAS_32_HEIGHT: u32 = 136;
pub(crate) const ICON_ATLAS_32_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-32.rgba"));
pub(crate) const ICON_ATLAS_36: ImageId = ImageId::from_raw(70036);
pub(crate) const ICON_ATLAS_36_WIDTH: u32 = 266;
pub(crate) const ICON_ATLAS_36_HEIGHT: u32 = 152;
pub(crate) const ICON_ATLAS_36_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-36.rgba"));
pub(crate) const ICON_ATLAS_42: ImageId = ImageId::from_raw(70042);
pub(crate) const ICON_ATLAS_42_WIDTH: u32 = 308;
pub(crate) const ICON_ATLAS_42_HEIGHT: u32 = 176;
pub(crate) const ICON_ATLAS_42_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-42.rgba"));
pub(crate) const ICON_ATLAS_48: ImageId = ImageId::from_raw(70048);
pub(crate) const ICON_ATLAS_48_WIDTH: u32 = 350;
pub(crate) const ICON_ATLAS_48_HEIGHT: u32 = 200;
pub(crate) const ICON_ATLAS_48_BYTES: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/icons/phosphor/atlas-48.rgba"));

pub(crate) const ICON_ATLASES: &[PhosphorAtlasEntry] = &[
    PhosphorAtlasEntry {
        image: ICON_ATLAS_16,
        physical_size: 16,
        width: 126,
        height: 72,
        bytes: ICON_ATLAS_16_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_20,
        physical_size: 20,
        width: 154,
        height: 88,
        bytes: ICON_ATLAS_20_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_24,
        physical_size: 24,
        width: 182,
        height: 104,
        bytes: ICON_ATLAS_24_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_28,
        physical_size: 28,
        width: 210,
        height: 120,
        bytes: ICON_ATLAS_28_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_30,
        physical_size: 30,
        width: 224,
        height: 128,
        bytes: ICON_ATLAS_30_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_32,
        physical_size: 32,
        width: 238,
        height: 136,
        bytes: ICON_ATLAS_32_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_36,
        physical_size: 36,
        width: 266,
        height: 152,
        bytes: ICON_ATLAS_36_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_42,
        physical_size: 42,
        width: 308,
        height: 176,
        bytes: ICON_ATLAS_42_BYTES,
    },
    PhosphorAtlasEntry {
        image: ICON_ATLAS_48,
        physical_size: 48,
        width: 350,
        height: 200,
        bytes: ICON_ATLAS_48_BYTES,
    },
];
