// @generated by tools/icon-atlas/generate-phosphor-icons.mjs

pub(crate) fn icon_image(icon: PhosphorIcon, logical_size: f32, scale_factor: f64) -> ImageId {
    let logical_size = nearest_logical_icon_size(logical_size);
    let physical_size = nearest_physical_icon_size(logical_size, scale_factor);
    ICON_ENTRIES
        .iter()
        .find(|entry| entry.icon == icon && entry.logical_size == logical_size && entry.physical_size == physical_size)
        .map_or_else(|| ICON_ENTRIES[0].image, |entry| entry.image)
}

fn nearest_logical_icon_size(size: f32) -> u32 {
    if size <= 20.0 { DENSE_ICON_LOGICAL_SIZE } else { STANDARD_ICON_LOGICAL_SIZE }
}

fn nearest_physical_icon_size(logical_size: u32, scale_factor: f64) -> u32 {
    let scale = if scale_factor.is_finite() && scale_factor > 0.0 { scale_factor } else { 1.0 };
    let target = (f64::from(logical_size) * scale).round();
    if let Some(entry) = ICON_ENTRIES
        .iter()
        .filter(|entry| entry.logical_size == logical_size)
        .filter(|entry| f64::from(entry.physical_size) >= target)
        .min_by_key(|entry| entry.physical_size)
    {
        return entry.physical_size;
    }
    ICON_ENTRIES
        .iter()
        .filter(|entry| entry.logical_size == logical_size)
        .max_by_key(|entry| entry.physical_size)
        .map_or(logical_size, |entry| entry.physical_size)
}
