// @generated by tools/icon-atlas/generate-phosphor-icons.mjs

use stern::core::{ImageId, Rect};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PhosphorIcon {
    Cursor,
    Move,
    Transform,
    Rotate,
    Cube,
    Play,
    Pause,
    Stop,
    Plus,
    Search,
    Archive,
    File,
    Image,
    Gear,
    Grid,
    Layers,
    Code,
    Box,
    Rocket,
    Download,
    Dots,
    Chevron,
    Caret,
    Reset,
    Component,
    Tokens,
    Eye,
    Crosshair,
}

pub(crate) struct PhosphorAtlasEntry {
    pub image: ImageId,
    pub physical_size: u32,
    pub width: u32,
    pub height: u32,
    pub bytes: &'static [u8],
}

pub(crate) struct PhosphorIconEntry {
    pub icon: PhosphorIcon,
    pub image: ImageId,
    pub symbol: &'static str,
    pub source_name: &'static str,
    pub logical_size: u32,
    pub physical_size: u32,
    pub atlas: ImageId,
    pub source: Rect,
}

pub(crate) const DENSE_ICON_LOGICAL_SIZE: u32 = 16;
pub(crate) const STANDARD_ICON_LOGICAL_SIZE: u32 = 24;
pub(crate) const ICON_ATLAS_PADDING: u32 = 1;
pub(crate) const ICON_ATLAS_COLUMNS: u32 = 7;
pub(crate) const ICON_COUNT: usize = 28;
