use super::{
    ABOUT_MODAL_DIALOG_TITLE, ABOUT_MODAL_PRODUCT_TITLE, ABOUT_MODAL_READINESS,
    ABOUT_MODAL_VERSION, ACTION_ABOUT, ACTION_ABOUT_CLOSE, ACTION_BUILD,
    ACTION_CANCEL_ACTIVE_FIXTURE_JOB, ACTION_CANCEL_QUEUED_FIXTURE_JOB, ACTION_DELETE,
    ACTION_DISMISS_FEEDBACK_REPORT, ACTION_DOCK_JOIN, ACTION_DOCK_SWAP, ACTION_DOCS,
    ACTION_DUPLICATE, ACTION_EXPORT, ACTION_GRID, ACTION_IMPORT_ASSET, ACTION_KEYBOARD_SHORTCUTS,
    ACTION_NEW_SCENE, ACTION_OPEN_FEEDBACK_REPORT, ACTION_OPEN_PROJECT, ACTION_PACKAGE_WINDOWS,
    ACTION_PALETTE, ACTION_PAUSE, ACTION_PLAY, ACTION_PREFERENCES, ACTION_PROJECT_SETTINGS,
    ACTION_QUIT, ACTION_REDO, ACTION_RUN_PROFILER, ACTION_SAVE, ACTION_SHOW_OVERLAYS, ACTION_STOP,
    ACTION_TOOL_MOVE, ACTION_TOOL_ROTATE, ACTION_TOOL_SCALE, ACTION_TOOL_SELECT, ACTION_UNDO,
    ACTION_VIEW_PERSPECTIVE, ACTION_VIEWPORT_FIT_CONTENT, ACTION_VIEWPORT_FIT_SELECTION,
    ACTION_VIEWPORT_FOCUS_SELECTED, ASSETS, ActionContext, ActionDescriptor, ActionId,
    ActionInvocation, ActionQueue, ActionSource, AssetSlotAsset, AssetSlotConfig, CornerRadius,
    DiagnosticSource, DiagnosticStrip, DiagnosticStripItem, DiagnosticStripSeverity,
    DockSplitterContextActionKind, DropdownItem, DropdownItemId, DropdownModel, Duration,
    EDITOR_TOOL_BUTTONS, EdgeDescriptor, EdgeId, EditorChromeMetrics, EditorInvocation,
    EditorMenuKind, EditorShowcase, EditorStatusItemKind, EditorTool, EditorToolbarGroupKind,
    EditorWorkflowScenes, FeedbackAction, FeedbackDismiss, FeedbackItem, FeedbackKind,
    FeedbackStack, FrameId, GraphPoint, GraphRect, GraphVector, JobCancel, JobList, JobPhase,
    JobProgress, JobRow, Key, KeyState, LOGS, ListLayout, Menu, MenuBar, MenuBarMenu,
    MenuBarOverlayRequest, MenuItem, MenuOverlay, ModalAction, ModalActionRole, ModalDialog,
    ModalDialogOverlay, NodeDescriptor, NodeFrameDescriptor, NodeFrameId, NodeGraphDescriptor,
    NodeGraphEdgeRoutePoint, NodeGraphEmissionError, NodeGraphPanZoom, NodeGraphSelection,
    NodeGraphSelectionTarget, NodeGraphStaticOutput, NodeGraphStaticView, NodeGraphViewport,
    NodeGroupDescriptor, NodeGroupId, NodeId, NumericScrubInputConfig, OverlayDismissal, OverlayId,
    OverlayKind, OverlayStack, PANEL_ASSETS, PANEL_CONSOLE, PANEL_INSPECTOR, PANEL_NODE_GRAPH,
    PANEL_SCENE, PANEL_TIMELINE, PANEL_VIEWPORT, PanelId, PanelOpenDecision, PanelTypeId,
    PanelWorkspaceContext, PathFieldConfig, PopoverPlacement, PortDescriptor, PortDirection,
    PortEndpoint, PortId, PortTypeId, PropertyGridRow, Rect, RepaintRequest, RerouteDescriptor,
    RerouteId, SelectFieldConfig, Size, StatusBar, StatusItem, StatusItemKind, StatusProgress,
    TOOLBAR_Y, TableColumn, TableLayout, Toolbar, ToolbarGroup, ToolbarIcon, ToolbarItem,
    ToolbarItemPresentation, Ui, Vec2, VectorScrubInputConfig, WORKFLOW_ASSET_ID_BASE, WidgetId,
    asset_browser, ctrl_char, diagnostic_item_id, dock, editor_dock_chrome_style,
    editor_dock_interaction_policy, editor_open_panel_metadata, editor_panel_instances,
    editor_panel_registry, editor_workspace_rect, feedback_id, feedback_kind_color,
    feedback_kind_label, inspector_grid_geometry, inspector_numeric_scrub, inspector_rows,
    inspector_value_label, item_id, job_phase_color, job_phase_label, job_row_id, log_color, menu,
    menu_action, menu_action_from_panel_metadata, menu_anchor, menu_bar_rect, menu_header_rects,
    menu_size, modal_action, outliner, paint_toolbar_icon_button_sized, panel_category_label,
    panel_type_for_open_action, rect, rect_fill, resolve_dock_splitter_context_actions_with_policy,
    rgb, rgba, run_toolbar_buttons, severity_color, severity_label, shortcut, shortcut_label,
    showcase_feedback_now, solve_dock_layout, solve_dock_splitters_with_style,
    status_item_text_width, text, toolbar_action, toolbar_icon_button, viewport,
    workflow_asset_model, workflow_outliner_model,
};

include!("showcase/core_chrome.rs");
include!("showcase/menus.rs");
include!("showcase/toolbar_workspace.rs");
include!("showcase/panels.rs");
include!("showcase/inspector_fixtures.rs");
include!("showcase/console_timeline_node_status.rs");
